### ISSUE TITLE
:snake:  :apple: :yum:

### ISSUE THREAD

**Issue by nnashiki** [rhoboro/github-actions#15]
we can use emoji :two_hearts:

**Comment by rhoboro** [comment]
Jekyllが対応してなさそうですね（笑）

**Comment by nnashiki** [comment]
いけるかなと思ったのですが、残念でした 😢

**Comment by rhoboro** [comment]
タイトルのレンダリングができてないみたいですね。リンクはありました（笑）
https://rhoboro.github.io/github-as-cms/2020/07/15/2020-07-15-15.html
<img width="552" alt="Screen Shot 2020-07-15 at 9 36 34" src="https://user-images.githubusercontent.com/13819005/87489729-b3074b00-c67e-11ea-8552-9f0c4bdd4ebf.png">
<img width="1528" alt="Screen Shot 2020-07-15 at 9 36 59" src="https://user-images.githubusercontent.com/13819005/87489755-c0bcd080-c67e-11ea-8881-38b8c7965cd1.png">
